services:
  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cnab
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
  api:
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cnab
      SPRING_ACTIVE_PROFILE: prod
    depends_on:
      - db
  spa:
    build: ./frontend/CNABProcessor
    ports:
      - "9090:9090"
    depends_on:
      - api