CREATE TABLE IF NOT EXISTS "transactions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" INT,
    "date" DATE,
    "value" DECIMAL(19,2),
    "cpf" VARCHAR(11),
    "card" VARCHAR(255),
    "hour" TIME,
    "store_owner" VARCHAR(255),
    "store_name" VARCHAR(255)
);